jdk:
    - oraclejdk7
install:
   - echo "Running a custom install command"
   - mvn install -DskipTests -Dmaven.test.skip=true
before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA_HOME=$JAVA7_HOME
